### ISSUE TITLE
Expose Version as a public field on beeline

### ISSUE THREAD

**Issue by paulosman** [honeycombio/beeline-go#102]
There should be a straightforward way to programmatically extract Version from beeline.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
