### ISSUE TITLE
Improve gRPC wrapper support

### ISSUE THREAD

**Issue by evanfuller** [honeycombio/beeline-go#202]
It looks like Honeycomb recently added support for a [unary server interceptor](https://github.com/honeycombio/beeline-go/blob/main/wrappers/hnygrpc/grpc.go#L93). I am interested in using Honeycomb to instrument some applications of mine that use gRPC, but they rely on client and server streaming.

It would be great if the `hnygrpc` package could implement the streaming server interceptor interface, as well as both the unary + streaming client interceptor interfaces.

**Comment by aarongable** [comment]
I have a PR (#217) which adds a UnaryClientInterceptor. It does not address the Streaming portion of this feature request.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
