### ISSUE TITLE
Separate client-span and trace-propagation concerns

### ISSUE THREAD

**Issue by aarongable** [honeycombio/beeline-go#272]
**Is your feature request related to a problem? Please describe.**

Currently, the http and grpc client wrappers perform two main functions:
1) They create new spans, to which information like request endpoints, response codes, and headers can be attached
2) They propagate the trace/span metadata across the connection to their corresponding server wrappers

These two functions are coupled; you can't get one without the other.

However, the creation and sending of client spans can (especially in a microservice architecture) nearly *double* the number of spans sent as part of a trace. The information contained in a client span -- headers, endpoint, etc -- is largely duplicated in the span sent by the server wrapper. This means that a team seeking to reduce its event volume might want to remove client spans from the equation, to get an easy 50% reduction in volume with little loss in data.

**Describe the solution you'd like**

A separation of concerns in the client wrappers. If appropriately configured, they should perform either (1), or (2), or both, as the user wants.

**Describe alternatives you've considered**

We tried using our sampler to simply discard client spans. However, because they're still _created_ and have their IDs sent across the network, the corresponding server spans all have no parent. This breaks the ability of the honeycomb UI to infer causality.

**Comment by vreynolds** [comment]
Hey @aarongable 👋 

We understand that outgoing request spans increase event volume, however, philosophically, we disagree that an instrumentation wrapper should allow disabling them. While it may be that server and client requests have data parity most of the time, we believe that a complete tracing solution ought to instrument both ends of the pipe, because when the server/client data diverges (e.g. networking issue) is a time when that data is most needed.

That being said, if you are set on not instrumenting outgoing requests, you should be able to create a homegrown roundtripper with just the trace propagation piece (the building blocks are public in the beeline).

My hunch here is that a tuned trace-aware sampling solution would do the trick (e.g. drop a percentage of 200/OK traces), but that generally requires an out-of-bounds process like [collector](https://github.com/open-telemetry/opentelemetry-collector) or [refinery](https://github.com/honeycombio/refinery).

**Comment by aarongable** [comment]
Fair enough! We already are doing significant sampling (around 1/300), and will soon be using Refinery to do so much more intelligently. But even so, this sort of separation of concerns would allow us to halve that sampling rate. But it makes sense that this isn't a knob that you want in upstream beeline, so we'll work on other solutions.
