### ISSUE TITLE
Consider option to specify which field value should go in 'name'?

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-go#36]
In the instrumentation for `sqlx` name gets populated by method names like `ExecContext` which is OK but it might be nice to be able to specify that a field like `db.query` is used instead.

Then you would see `SELECT * FROM ...` in the name column and reasoning about sequences of queries would be easier. Or, maybe it would be nice to somehow have a dataset level setting for which fields should be unrolled by default and set it there. Not sure how I'd approach this one.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
