### ISSUE TITLE
The SQL wrapper should not call libhoney's singleton, package-level functions

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/beeline-go#62]
Tangentially related to #55. When we upgraded to the latest master of beeline-go some of our apps stopped reporting SQL events:

<img width="1515" alt="Image 2019-05-08 at 11 48 41 am" src="https://user-images.githubusercontent.com/20394/57370550-4e9e5100-7188-11e9-90ef-1e2902cb5f2e.png">

It seems that only the functions that don't accept a `context.Context` stopped reporting. I think this is because the wrapper [is calling singleton methods on `libhoney-go`](https://github.com/honeycombio/beeline-go/blob/e94ac5979b4174b3355000834df8e4d48d9393f2/wrappers/hnysql/sql.go#L31), but `beeline-go` no longer initializes `libhoney-go`'s global Client, so the events are being silently dropped. Maybe the wrappers should use `github.com/honeycombio/beeline-go/client` instead?

In the meantime I'm taking this as a kick to change our app to use the context-ful variant 😅.

**Comment by BRMatt** [comment]
Just discovered this is also happening in the net/http transport wrapper https://github.com/honeycombio/beeline-go/blob/master/wrappers/hnynethttp/nethttp.go#L106

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
