### ISSUE TITLE
Consider adding HTTP referrer?

### ISSUE THREAD

**Issue by danyelf** [honeycombio/beeline-go#64]
Currently, the Go Beeline doesn't capture http referrer. That might be an interesting case -- would it be worth adding the 'Referrer' header field? (I can imagine some people might have privacy issues)

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
