### ISSUE TITLE
The net/http Transport wrapper should allow you to attach extra metadata to spans

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/beeline-go#71]
There are some situations where it's helpful to record extra, arbitrary information about http requests and responses to the spans created by the `net/http` Transport wrapper.

In some of our systems we've found that third party APIs often return incredibly useful metadata in HTTP response headers, e.g.:

- the version of their API that serviced the request
- region that serviced the HTTP request
- deprecation warnings about API usage
- details of rate limit consumption/allowance
- some of our internal apps return the route pattern/shape they used to match the request, which makes it easier to group HTTP calls made by a http client

To implement this right now you'd have to create another roundtripper that sits between the honeycomb transport and the default `net/http.Client{}.Transport`, which seems unnecessarily awkward/adds yet more wrappers to `net/http.Client{}.Transport`.

It'd be nice if the beeline transport offered an explicit way to extract and add this metadata, e.g.:

```
hnynethttp.WrapRoundTripperWithMetadataHook(http.RoundTripper, func(http.Request, *http.Response, error) map[string]interface{})
```

I guess prior art for this would be the `PresendHook` on the Config struct?

**Comment by BRMatt** [comment]
Actually, what about if the span was passed directly to the callback instead of the hook returning a map of metadata? e.g.

```
func(trace.Span, http.Request, *http.Response, error)
```
That way the hook could even rollup data into the trace?

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
