### ISSUE TITLE
Consider devirtualizing Timer

### ISSUE THREAD

**Issue by alex** [honeycombio/beeline-go#80]
Currently Timer is an interface, and there's a comment saying:

> // Represented
> // as an interface so that other implementations can do fancy things with the
> // values in addition to just returning them, such as submit them to
> // instrumentation frameworks.

However that doesn't seem to be how the design of the code has evolved, timers are not responsible for submitting values.

I think it'd make sense to devirtualize this (i.e. change from an interface to a concrete struct), which should be good for performance.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
