### ISSUE TITLE
Ovveride logger without replacing the libhoney client

### ISSUE THREAD

**Issue by gianarb** [honeycombio/beeline-go#83]
Hello!
I was looking around in this library and I saw that libhoney accept a logger. But the `libhoney.Client` gets set during the `beeline.Init`. It means that in order to replace the Logger I need to override all Client. If I am reading it right. It does not sound friendly.

What if I add a `Logger` as part of the `beeline.Config`? In this way, it can be passed into the `libhoney.Client`.

Let me know if so I can do a PR.

**Comment by maplebed** [comment]
I'm hesitant. The presence of config settings in the beeline that are duplicating those on a client is something I'd like to phase out.

The evolution went:
* beeline is written before libhoney has clients
* beeline gets a few chosen configs that override the libhoney defaults
* libhoney gets a `Client`
* beeline allows you to set the client but doesn't remove chosen configs that predated it
* we're now in the confusing state of being able to set things in multiple places

I think if work is going to be put in to this area, making setting a client more friendly would be more valuable than adding additional special fields that override the client. Longer term I would like to deprecate then remove all the settings that are duplicated in the beeline config and the client config so that it is more clearly "default settings" or "user-defined client" and not a mesh of two different sets of defaults. 

That said, the approach of "don't do something small and useful now because of something big and far away that might replace it" is a trap and so I could probably be convinced to slip a bit along this slope.  

Would you be interested in trying out using a Client for a bit and see if it really is unfriendly?

**Comment by gianarb** [comment]
Sure! I understand the end goal and I think it is reasonable, I will try to use the client and if I can find a good way to make it easier to set I will share it.

Closing for now
