### ISSUE TITLE
Allow modification of trace fields prior to serializing trace context

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/beeline-go#84]
Our internal services propagate an identity token that represents the user/principal in our system that started the RPC call. Our systems add information from this token to the trace using `AddFieldToTrace()`, so that every span in the trace has that information.

When we're propagating trace context between processes there's little reason for us to include that information in the `x-honeycomb-trace` context as the upstream is going to re-extract it from the identity token and add it to its own part of the trace.

On internal GET requests/rpcs the identity token and honeycomb trace context accounts for a reasonable part of the payload, so it seems unnecessary to duplicate that information.

It would be good if we could specify a hook in the beeline that allows us to remove fields from the context prior to them being encoded, ala the `PresendHook`.

See slack discussion: https://honeycombpollinators.slack.com/archives/CLXQWT35J/p1574862771056800

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
